cart/urls.py
from django.conf.urls import include, url
from . import views

urlpatterns = [
    url(r'^$', views.show_cart, name='show_cart'),
]

catalog/urls.py
from django.conf.urls import include, url
from catalog import views
 
urlpatterns = [
    url(r'^category/(?P<category_slug>[-\w]+)/$', views.show_category, name='catalog_category'),
    url(r'^product/(?P<product_slug>[-\w]+)/add-comment/$', views.add_comment, name='add_comment'),
    url(r'^product/(?P<product_slug>[-\w]+)/$', views.show_product, name='catalog_product'),
]

djangocms/urls.py
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/', include('registration.backends.simple.urls')),
    url(r'^accounts/', include('allaccess.urls')),
    url(r'^cart/', include('cart.urls')),
    url(r'', include('catalog.urls')),
    url(r'', include('main.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.conf.urls import url
from django.views.generic import RedirectView

urlpatterns = [
    # redirect to category: All
    url(r'^$', RedirectView.as_view(pattern_name='catalog_category'), name='main_home', kwargs={'category_slug':'all'}),
]

cart/models.py
from django.db import models
from catalog.models import Product

class CartItem(models.Model):
    cart_id = models.CharField(max_length=50)
    date_added = models.DateTimeField(auto_now_add=True)
    quantity = models.IntegerField(default=1)
    product = models.ForeignKey('catalog.Product', unique=False)

    def total(self):
        return self.quantity * self.product.price

    def name(self):
        return self.product.name

    def price(self):
        return self.product.price

    def get_absolute_url(self):
        return self.product.get_absolute_url()

    def augment_quantity(self, quantity):
        self.quantity = self.quantity + int(quantity)
        self.save()

    class Meta:
        db_table = 'cart_items'
        ordering = ['date_added']

catalog/models.py
from __future__ import unicode_literals
from django.core.urlresolvers import reverse
from django.db import models

class Category(models.Model):
    name = models.CharField(max_length=50)
    slug = models.SlugField(max_length=50, unique=True, help_text='Unique value for product page URL, created from name.')
    description = models.TextField()

    def __unicode__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('catalog_category', args=(self.slug,))

    class Meta:
        db_table = 'categories'
        ordering = ['name']
        verbose_name_plural = 'Categories'

class Product(models.Model):
    name = models.CharField(max_length=255, unique=True)
    slug = models.SlugField(max_length=255, unique=True, help_text='Unique value for product page URL, created from name.')
    brand = models.CharField(max_length=50)
    price = models.DecimalField(max_digits=9, decimal_places=2)
    image = models.FileField(upload_to='./product_img/')
    quantity = models.IntegerField()
    description = models.TextField()
    categories = models.ManyToManyField(Category)

    def __unicode__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('catalog_product', args=(self.slug,))

    class Meta:
        db_table = 'products'
        ordering = ['name']


class Comment(models.Model):
    text = models.TextField()
    author = models.CharField(max_length=255)
    publish_date = models.DateTimeField(auto_now=True)
    product = models.ForeignKey(Product)

    def __unicode__(self):
        return self.text

    class Meta:
        db_table = 'comments'

cart/forms.py
from django import forms 
 
class ProductAddToCartForm(forms.Form):
    quantity = forms.IntegerField(widget=forms.TextInput(attrs={'size':'2', 'value':'1', 'class':'quantity', 'maxlength':'5'}), error_messages={'invalid':'Please enter a valid quantity.'}, min_value=1)
    product_slug = forms.CharField(widget=forms.HiddenInput())

    # override the default __init__ so we can set the request
    def __init__(self, request=None, *args, **kwargs):
        self.request = request
        super(ProductAddToCartForm, self).__init__(*args, **kwargs)

    # custom validation to check for cookies
    def clean(self):
        if self.request:
            if not self.request.session.test_cookie_worked():
                raise forms.ValidationError("Cookies must be enabled.")
            return self.cleaned_data

cart/views.py
from django.shortcuts import render

# Create your views here.
from django.shortcuts import render_to_response
from . import cart_logic

def show_cart(request):      
    if request.method == 'POST':
        postdata = request.POST.copy()
        if postdata['submit'] == 'Remove':
            cart_logic.remove_from_cart(request)
        if postdata['submit'] == 'Update':
            cart_logic.update_cart(request)
    cart_items = cart_logic.get_cart_items(request)
    cart_subtotal = cart_logic.cart_subtotal(request)
    return render(request, 'cart/cart.html', locals())

catalog/views.py
from django.shortcuts import get_object_or_404, render
from django.core import urlresolvers
from django.http import HttpResponseRedirect, HttpResponseNotFound
from cart.forms import ProductAddToCartForm
from cart import cart_logic
from catalog.models import Category, Product, Comment

# Create your views here.
def show_category(request, category_slug):
    category = get_object_or_404(Category, slug=category_slug)
    products = category.product_set.all()
    request.session.set_test_cookie()
    return render(request, 'catalog/category.html', locals())

def show_product(request, product_slug):
    p = get_object_or_404(Product, slug=product_slug)
    categories = p.categories.all()
    comments = Comment.objects.filter(product=p).order_by('-publish_date')
    # need to evaluate the HTTP method
    if request.method == 'POST':
        # add to car create the bound form
        postdata = request.POST.copy()
        form = ProductAddToCartForm(request, postdata)
        #check if posted data is valid
        if form.is_valid():
            #add to cart and redirect to cart
            cart_logic.add_to_cart(request)
            # if test cookie worked, get rid of it
            if request.session.test_cookie_worked():
                request.session.delete_test_cookie()
                url = urlresolvers.reverse('show_cart')
                return HttpResponseRedirect(url)
    else:
        # it's a GET create the unbound form. Note request as a kwarg
        form = ProductAddToCartForm(request=request, label_suffix=':')
    # assign the hidden input the product slug
    form.fields['product_slug'].widget.attrs['value'] = product_slug
    # set the test cookie on our first GET request
    request.session.set_test_cookie()
    return render(request, 'catalog/product.html', locals())

def add_comment(request, product_slug):
    if request.method == 'POST':
        p = get_object_or_404(Product, slug=product_slug)
        text = request.POST.get('text')
        comment = Comment(text=text, author=request.user.username, product=p)
        comment.save()
        url = urlresolvers.reverse('catalog_product', kwargs={'product_slug':product_slug})
        return HttpResponseRedirect(url)
    else:
        return HttpResponseNotFound()
    

cart/templates/cart/cart.html
{% extends "base.html" %} {% block title %}Shopping cart{% endblock %} {% block content %}
<div class="container">
    <div class="row">
        <h1>Shopping cart</h1>
    </div>
    <div class="row">
        <table class="table table-hover table-striped">
            <thead>
                <tr>
                    <th>Product</th>
                    <th>Price</th>
                    <th></th>
                    <th class="text-right">Total</th>
                </tr>
            </thead>
            <tfoot>
                <tr>
                    <th class="text-right" colspan="3">Cart Subtotal: </th>
                    <th class="text-right">${{ cart_subtotal }}</th>
                </tr>
            </tfoot>
            <tbody>
                {% if cart_items %} 
                {% for item in cart_items %}
                <tr>
                    <td><a href="{{ item.get_absolute_url }}">{{ item.name }}</a></td>
                    <td>${{ item.price }}</td>
                    <td>
                        <form method="post" action="." class="form-inline" style="display: inline-block">
                            {% csrf_token %}  
                            <label for="quantity">Quantity:</label> 
                            <input type="text" class="form-control input-sm" name="quantity" value="{{ item.quantity }}" id="quantity" size="2" class="quantity" maxlength="5" />
                            <input type="hidden" name="item_id"value="{{ item.id }}" />
                            <input type="submit" class="btn btn-sm btn-success" name="submit" value="Update" />
                        </form>
                        <form method="post" action="." class="form-inline" style="display: inline-block">
                            {% csrf_token %}  
                            <input type="hidden" class="form-control input-sm" name="item_id" value="{{ item.id }}" />
                            <input type="submit" class="btn btn-sm btn-danger" name="submit" value="Remove"/>
                        </form>
                    </td>
                    <td class="text-right">${{ item.total }}</td>
                </tr> {% endfor %}
                {% else %}
                <tr>
                    <td colspan="6">Your cart is empty.</td>
                </tr> 
                {% endif %}
            </tbody>
        </table>
    </div>
</div>
{% endblock %}

cart/templates/cart/cart_box.html
{% with cart_item_count as cart_count %}       
    <a href="{% url 'show_cart' %}">Shopping cart {% if cart_count %}<span class="badge">{{ cart_count }}</span>{% endif %}</a> 
{% endwith %}

catalog/templates/catalog/category.html
{% extends "base.html" %} {% block title %}{{ category.name }}{% endblock %} {% block content %}
<div class="container">
    {% comment %}
    <div class="row">
        {% for product in products %}
        <div>
            <a href="{{ product.get_absolute_url }}">{{ product.name }}</a>
        </div>
        {% endfor %}
    </div>
    {% endcomment %}
    <div class="row">
        {% for product in products %}
        <div class="col-sm-6 col-md-4">
            <div class="thumbnail">
                <img class="product-thumbnail-img" src="/media/{{ product.image }}">
                <div class="caption product-thumbnail-caption">
                    <h3>{{ product.name }}</h3>
                    {{ product.description }}
                </div>
                <div class="caption" style="margin-top: 5px;">
                    <div>
                        <a href="{{ product.get_absolute_url }}" class="btn btn-default" role="button">Read more..</a>

                        <form method="post" action="{{ product.get_absolute_url }}" class="pull-right">
                            {% csrf_token %}
                            <input id="id_quantity" name="quantity" type="hidden" value="1">
                            <input id="id_product_slug" name="product_slug" type="hidden" value="{{ product.slug }}">
                            <input class="btn btn-primary" type="submit" value="Add To Cart!" name="submit">
                        </form>
                    </div>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

catalog/templates/catalog/category_list.html
{% with active_categories as cats %}
<li class="dropdown">
    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Categories <span class="caret"></span></a>
        <ul class="dropdown-menu">
        {% for c in cats %}
            {% ifequal c.get_absolute_url request_path %} 
            <li class="active"><a>{{ c.name }}</a></li>
            {% else %} 
            <li><a href="{{ c.get_absolute_url }}">{{ c.name }}</a></li>
            {% endifequal %} 
        {% endfor %}
        </ul>
    </li>
{% endwith %}

catalog/templates/catalog/product.html
{% extends "base.html" %} {% block title %}{{ p.name }}{% endblock %} {% block content %}
<div class="container">
    <div class="row">
        <div class="col-xs-12 col-sm-6">
            <h1>{{ p.name }}</h1>
            <h4>Brand: <em>{{ p.brand }}</em></h4>
            <div> 
                In categor{{ categories.count|pluralize:"y,ies" }}: 
                {% for c in categories %}
                    <a href="{{ c.get_absolute_url }}">{{ c.name }}</a> {% if not forloop.last %}, {% endif %} 
                {% endfor %}
            </div>

            <div style="margin-top: 30px;"><h4>Price: $ {{ p.price }}</h4></div>
            <form method="post" action="." class="form-inline">
                {% csrf_token %} 
                <input id="id_product_slug" name="product_slug" type="hidden" value="{{ p.slug }}">
                <label for="id_quantity">Quantity:</label> 
                <input class="form-control input-sm" style="max-width: 50px" id="id_quantity" maxlength="5" name="quantity" size="2" type="text" value="1" required="">
                <input class="btn btn-sm btn-success" type="submit" value="Add To Cart" name="submit" alt="Add To Cart">
            </form>
        </div>
        <div class="col-xs-12 col-sm-6">
            <img class="product-full-img center-block" src="/media/{{ p.image }}" />
        </div>
    </div>
    <div class="row col-xs-12">
        <h3>Product Description</h3>
        <p>{{ p.description }}</p>
    </div>

    <div class="row col-xs-12 col-sm-5">
        <h3>Comments</h3>
            {% if request.user.is_authenticated %}
                <div class="panel panel-default">
                    <div class="panel-body">
                        <form method="post" action="./add-comment/">
                            {% csrf_token %} 
                            <input id="id_product_slug" name="product_slug" type="hidden" value="{{ p.slug }}">
                            <textarea class="form-control" id="id_text" name="text" placeholder="Share your opinion" rows="3" required=""></textarea>
                            <button class="btn btn-default pull-right" style="margin-top: 10px;" type="submit">Submit comment</button>
                        </form>
                    </div>
                </div>
            {% else %}
                <div class="panel-body">
                    <p style="margin-top: 10px;">You need to <a href="{% url 'auth_login' %}">login</a> to add your comment</p>
                </div>
            {% endif %}
            {% for cs in comments %}
                <div class="panel panel-default">
                    <div class="panel-body">
                        <div><strong>{{ cs.author}}</strong> <span class="text-muted">commented {{ cs.publish_date }}</span></div>
                        <p style="margin-top: 10px;">{{ cs.text }}</p>
                    </div>
                </div><!-- /panel panel-default -->
            {% endfor %}  
    </div>
</div>
{% endblock %}

main/templates/base.html
{% load staticfiles %}
{% load cart_tags %}
{% load catalog_tags %}
<!DOCTYPE html>

<html>

<head>
    <title>Music store - {% block title %}Home{% endblock title %}</title>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css">
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
</head>

<body>
    <nav class="navbar navbar-inverse navbar-static-top">
        <div class="container-fluid">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false"
                    aria-controls="navbar">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="{% url 'main_home' %}">Music Store </a>
            </div>
            <div id="navbar" class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a href="{% url 'catalog_category' category_slug='all' %}">Browse all products</a></li>
                    {% category_list request.path %}
                </ul>
                <ul class="nav navbar-nav navbar-right">                    
                    {% if request.user.is_authenticated %}
                    <li><p class="navbar-text">Welcome '{{ request.user.get_full_name|default:request.user.username }}'</p></li>
                    <li><a href="{% url 'auth_logout' %}">Logout</a></li>
                    {% else %}
                    <li><a href="{% url 'auth_login' %}">Login</a></li>
                    {% endif %}
                    <li>{% cart_box request %}</li>
                </ul>
            </div>
            <!--/.nav-collapse -->
        </div>
        <!--/.container-fluid -->
    </nav>

    {% block content %}{% endblock content %}
</body>

</html>